### ISSUE TITLE
Can't change install location

### ISSUE THREAD

**Issue by zimmah** [decred/Paymetheus#235]
There is no option to change the install path or even the drive.   
Manually moving the program after installing causes errors.   
It's really unconventional to force someone to install in a specific direction, And I much prefer to install it on a different drive.   
It's bad practice to force a specific location.

**Comment by jrick** [comment]
Sorry, this is an installer issue, not a paymetheus one.

The installer installs to your program files directory.  This is standard practice.  If you want it somewhere else, move your program files.

**Comment by marcopeereboom** [comment]
I strongly disagree with the stated opinion of a need to install files to a specific location.  The 90s have come and gone and nowadays an OS requires one to install binaries and supporting files in specific locations.  Our MSI does exactly that.  As you have noticed; moving files around does not work, this is expected without surgery in the apps.

**Comment by zimmah** [comment]
I don't want random files on my C:\ drive, I want to install it on my D:\ drive.    
It's my fucking computer, let me decide where I install stuff.   
What kind of User Experience is it when I am forced to install on a specific location?

**Comment by pedrotst** [comment]
Honestly this makes no sense whatsoever. My work computer has very litle C:\ drives because of cheaper SSDs and we need to install everything on D for an instance.

We could do it so far with every single installer needed, so the argument that "OS requires one to install binaries and supporting files in specific locations" could not be more flawed. 

Maybe the files at AppData ok, user doesn't manage where those goes, but the instalation folder? No no.

**Comment by marcopeereboom** [comment]
Binaries go in %programfiles% data goes in %appdata%.  Binaries are only a couple of megs.

dcrinstall (the CLI installer) lets you put binaries where you want but it does not install paymetheus.

**Comment by zimmah** [comment]
It's incredibly hard to move %Programfiles% though, and this is literally the only program that doesn't allow me to change the install path.    
I think user experience is a large factor in success of altcoins, because the competition is fierce, so these kind of issues that may seem minor to you could have a huge impact on the success of decred.  
The lower the barrier to entry is, the better it is for everyone who holds decred.

**Comment by marcopeereboom** [comment]
I am not being ugly.  We are doing things the Microsoft way.  And while this may look like a minor issue to you this is a massive amount of corner-case code that will never be exactly right.  Microsoft forces these things, these days, for exactly those reasons.  They don't want to field support tickets because a user moved applications to another location.

I understand that legacy windows power users think they know better but your friendly OS vendor disagrees.

And I can not stress enough that the data location can be modified.

Over and out.

**Comment by davecgh** [comment]
I have to agree with the other user's here as I've already mentioned in chat.  Practically every installer in existence allows you to specify the drive, typical behind an "advanced" or "custom" option.  There is simply no reason not to allow a separate drive to be specified.  There are many, many reasons not to install to program files.
