### ISSUE TITLE
Pool fee should be settable even for registered pools

### ISSUE THREAD

**Issue by mverrilli** [decred/Paymetheus#239]
Pool fee percent is actually the minimum allowed percent for that pool. The value should be settable for registered pools with a minimum value per the pool fee from api for that pool, but allowed to be set higher by the user if they intend to pay more than the minimum required fee.

**Comment by jrick** [comment]
No, sorry.  The pool fee is the percentage of the reward that you pay to the pool, not what is paid per transaction to get your ticket purchases mined.  There is no advantage at all to allowing users to waste their money by paying more to the pool.

**Comment by mverrilli** [comment]
Well, my pool allows you to choose what you'd like to give the pool and as such has its setting at the lowest possible minimum value.

**Comment by jrick** [comment]
You should set up a donation address then.  We won't be adding this.

**Comment by jrick** [comment]
I don't want to encourage it, but it is also possible for users to use the manual stakepool purchasing to use a fee higher than the minimum.  The reason I don't want to encourage this however isn't so that knowledgeable users can't pay more than required, but because we will be adding more features (like vote preferences) that require the stakepool API in the future.

I still think that a donation address is your best bet (you might even get more than some percentage of your users' rewards) but if you feel like it's necessary for users to pay a higher fee percentage of their reward, it will be on you to document how to do this with the manual stakepool integration.

**Comment by mverrilli** [comment]
Thanks. Yep, I'm working on an instruction on how to set up the manual stakepool now (just waiting on the wallet to sync up so I can take screenshots). I didn't know about the vote preferences using the API, though, so I guess I'll watch that carefully to see what's going on there.  I'll try out the donation address, too.
