### ISSUE TITLE
Purchasing tickets does not always work

### ISSUE THREAD

**Issue by SteffenIvanhoe** [decred/Paymetheus#285]
Have bought some stake mining tickets. It worked. But now I have a problem. It does not work any longer. Despite having enough funds available, I always get the message "Unable to purchase tickets: insufficient funds available to construct transaction". I have 91 Decred "spendable" and the ticket price is 52. Looks like a bug.

Is there a known workaround?

**Comment by jrick** [comment]
No workaround, the bug is probably the incorrectly reported spendable balance.

If you have purchased tickets previously, you must wait 256 blocks before the vote or revocation transaction's outputs mature and can be spent.  This may be what is causing the errors, as immature outputs can not be used to construct the transaction yet and your actual spendable balance is lower than reported.

See #225
