### ISSUE TITLE
Clicking on amount in create transaction throws an empty exception

### ISSUE THREAD

**Issue by marcopeereboom** [decred/Paymetheus#53]
When clicking on the amount edit box code throws an empty exception.

It is at CreateTransactionViewModel.cs line 99

An exception of type 'Paymetheus.Decred.Wallet.AddressException' occurred in Paymetheus.exe but was not handled in user code

**Comment by jrick** [comment]
I'm not sure this is a bug.  If the string in either the address or amount textboxes can not be parsed as an address or amount, an exception will be thrown.  While the application code does not catch this exception, the framework does and should put a red box around the textbox indicating that the input was invalid.

The address and amount parsing code will run anytime focus leaves the textbox, or the enter key is pressed.

The visual studio debugger pauses the program because no application logic catches the exception, but if you hit continue, the application will continue running and the exception caught by the WPF libraries.

**Comment by marcopeereboom** [comment]
After rereading the code I agree.  Sorry about the noise.
