### ISSUE TITLE
Fee calculation is not obvious

### ISSUE THREAD

**Issue by marcopeereboom** [decred/Paymetheus#68]
When calculating a fee for a transaction the cost is not obvious to casual users.

IMO, casual users would expect the fee to be based on amount, not transaction size.

No one expects the spanish inquisition!

**Comment by marcopeereboom** [comment]
Add label explaining how this works.  Nothing fancy.

**Comment by jrick** [comment]
Should this label always be visible, or do we want to give the user some way of interacting with the program to show it (like hovering over some element to show a tooltip)?

I pretty much hate tooltips since they are only usable by users with a mouse (adding a Flyout to a Button in UWP apps is much better in my opinion, however there is no Flyout equivalent for WPF), so that's something to consider.

Another possibility is to add a "how are fees calculated?" hyperlink that opens a browser to docs.decred.org with the full details.
