### ISSUE TITLE
use installed dcrwallet.exe

### ISSUE THREAD

**Issue by marcopeereboom** [decred/Paymetheus#97]
The msi installs dcrwallet.exe in the same directory as paymetheus.exe. We should try to run dcrwallet from the same path first.

We may want to disallow running a dcrwallet from anywhere else however, that makes testing hard. Think about this some more.

**Comment by jrick** [comment]
I'd recommend using an absolute path instead of a relative one (`.\dcrwallet.exe`) in case Paymetheus is somehow started with a different working directory.  Starting a malicious wallet binary can be fatal.

For testing I'd recommend adding another command line flag that either specifies the absolute location of the wallet binary or searches for it in the PATH.
